######################## default configuration ####################
baseURL = "https://jimchien666.github.io/"
languageCode = "zh-tw"
title = "JimChien"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu

  [[menu.main]]
  name = "文章"
  URL = "blog"
  weight = 1

  [[menu.main]]
  name = "讀書清單"
  URL = "booklist"
  weight = 2
  [[menu.main]]
  name = "關於我"
  URL = ""
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Jim Chien"
# Google Analitycs
googleAnalitycsID = "Your ID"

# copyright
copyright = "| copyright &copy; 2021 [Themefisher](https://themefisher.com/hugo-themes/) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true



############################# social site ########################

[[params.social]]
title = "github"
icon = "ti-github" 
link = "https://github.com/JimChien666"

[[params.social]]
title = "twitter"
icon = "ti-twitter" 
link = "https://github.com/JimChien666"

[[params.book]]
title = "30天與Docker做好朋友"
link = "#"
type = "書"
status = "未讀"
share = "想分享"

[[params.book]]
title = "A Software Developer's Guide to HTTP"
link = "https://odetocode.com/Articles/741.aspx"
type = "文章"
status = "已讀"
share = "想分享"

[[params.book]]
title = "Laravel 原始碼分析"
link = "https://mileschou.github.io/ironman/2019/analyze-laravel"
type = "文章"
status = "未讀"
share = "想分享"

[[params.book]]
title = "Cryptography I"
link = "https://www.coursera.org/learn/crypto/home/welcome"
type = "線上課程"
status = "學習中"
share = "想分享"


[[params.myarticle]]
title = "跟著官方文件學習Laravel, 並實作出一個會員登入系統"
link = "https://ithelp.ithome.com.tw/users/20141109/ironman/4412"
[[params.myarticle]]
title = "測試初體驗"
link = "https://hackmd.io/DiVJGOd-Q9Cw0q_B5dkeRA"


[[params.learn]]
title = "第 1 週"
start = "2021/11/1"
end = "2021/11/7"
status = ""
[[params.learn]]
title = "第 2 週"
start = "2021/11/8"
end = "2021/11/14"
status = ""
[[params.learn]]
title = "第 3 週"
start = "2021/11/15"
end = "2021/11/21"
status = ""
[[params.learn]]
title = "第 4 週"
start = "2021/11/22"
end = "2021/11/28"
status = ""
[[params.learn]]
title = "第 5 週"
start = "2021/11/29"
end = "2021/12/5"
status = ""
[[params.learn]]
title = "第 6 週"
start = "2021/12/6"
end = "2021/12/12"
status = ""
[[params.learn]]
title = "第 6 週"
start = "2021/12/13"
end = "2021/12/20"
status = ""